# Generated by Django 5.2.4 on 2025-07-02 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('photos', models.CharField(max_length=100)),
                ('pourcentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Biere',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cave_backend.item')),
                ('variety', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
            ],
            bases=('cave_backend.item',),
        ),
        migrations.CreateModel(
            name='Chocolat',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cave_backend.item')),
                ('color', models.CharField(max_length=10)),
            ],
            bases=('cave_backend.item',),
        ),
        migrations.CreateModel(
            name='Spirits',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cave_backend.item')),
                ('variety', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
            ],
            bases=('cave_backend.item',),
        ),
        migrations.CreateModel(
            name='Vine',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cave_backend.item')),
                ('couleur', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('variety', models.CharField(max_length=100)),
            ],
            bases=('cave_backend.item',),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChartItem',
            fields=[
                ('quantity', models.IntegerField()),
                ('pk', models.CompositePrimaryKey('item_id', 'chart_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cave_backend.chart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cave_backend.item')),
            ],
        ),
    ]
