# Generated by Django 5.2.3 on 2025-07-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cave_backend', '0002_tag_delete_alliances_delete_taste'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='selection',
            field=models.BooleanField(default=False),
        ),
    ]
